name: vcs_portal
description: A Flutter login/register app connected to Flask and MySQL.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/background.png
    - assets/images/vc_drone_view.png
    - assets/images/VC_icon.png
  uses-material-design: true